package util;

public class AlexaSites
{
	public final static String[] SITES = {
			"https://www.google.com/?gws_rd=ssl",
			"https://www.facebook.com",
			"https://www.youtube.com",
			"https://www.yahoo.com",
			"http://www.baidu.com",
			"http://en.wikipedia.org/wiki/Main_Page",
			"http://www.amazon.com",
			"https://twitter.com",
			"http://www.taobao.com/market/global/index_new.php",
			"http://www.qq.com",
			"https://www.google.co.in",
			"https://login.live.com/",
			"https://www.linkedin.com",
			"http://www.sina.com",
			"http://weibo.com/login.php",
			"http://www.yahoo.co.jp",
			"http://www.tmall.com",
			"https://www.google.co.jp/?gws_rd=ssl",
			"http://www.ebay.com",
			"https://www.blogger.com/home",
			"http://t.co",
			"https://www.google.de/?gws_rd=ssl",
			"http://www.yandex.ru",
			"http://www.hao123.com",
			"http://www.bing.com",
			"http://vk.com",
			"http://www.reddit.com",
			"https://www.google.co.uk/?gws_rd=ssl",
			"http://www.msn.com",
			"http://www.amazon.co.jp",
			"https://www.google.com.br/?gws_rd=ssl",
			"https://instagram.com",
			"https://www.google.fr/?gws_rd=ssl",
			"https://www.tumblr.com",
			"https://wordpress.com",
			"http://sohu.com",
			"http://imgur.com",
			"https://www.pinterest.com",
			"http://paypal.com",
			"http://www.aliexpress.com",
			// "http://www.xvideos.com",
			"http://www.ask.com",
			"http://www.apple.com",
			"http://www.microsoft.com/en-us/default.aspx",
			"http://onclickads.net",
			"https://mail.ru",
			"https://www.google.ru/?gws_rd=ssl",
			"https://mail.google.com",
			"https://www.google.it/?gws_rd=ssl",
			"http://www.imdb.com",
			"http://www.alibaba.com",
			"http://fc2.com",
			"https://www.adcash.com/en/index.php",
			"https://www.google.es/?gws_rd=ssl",
			"http://www.amazon.de",
			"http://360.cn",
			"http://stackoverflow.com",
			"https://www.netflix.com/us/",
			// "http://www.googleadservices.com",
			"http://diply.com",
			"http://raleigh.craigslist.org",
			"https://www.google.ca/?gws_rd=ssl",
			"http://go.com",
			// "http://xhamster.com",
			"http://www.naver.com",
			"https://www.google.com.hk",
			"http://tianya.cn",
			"http://163.com",
			"http://gmw.cn",
			"http://www.bbc.com",
			// Exception in thread "main" javax.net.ssl.SSLException: hostname
			// in certificate didn't match: <kickass.to> != <*.kickass.so> OR
			// <*.kickass.so> OR <kickass.so>
			// "https://kickass.to",
			"https://www.google.com.tr/?gws_rd=ssl",
			"http://www.amazon.co.uk",
			// "http://www.pornhub.com",
			"http://www.rakuten.co.jp",
			"http://www.adobe.com",
			"http://www.ebay.de",
			"http://ok.ru",
			"https://www.google.com.mx/?gws_rd=ssl",
			"http://www.amazon.cn",
			"http://www.dropbox.com",
			"http://www.cnn.com",
			"http://www.nicovideo.jp",
			"https://www.google.pl/?gws_rd=ssl",
			"http://www.dailymotion.com/us",
			"https://www.google.com.au/?gws_rd=ssl",
			"http://espn.go.com",
			"http://soso.com", // http://www.sogou.com/?rfrom=soso
			"http://www.cntv.cn",
			// "http://www.googleusercontent.com",
			"http://www.jd.com", "https://github.com",
			"http://www.outbrain.com", "http://www.directrev.com",
			"http://www.youku.com", "https://www.alipay.com",
			"http://people.com.cn", "https://www.pixnet.net",
			"http://www.flipkart.com", "https://www.google.co.kr/?gws_rd=ssl", };
}
